[build]
  command = "npm install --legacy-peer-deps --force && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/hoodiehut/"
  to = "/collective/hoodiehut/"